# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meterValue.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='meterValue.proto',
  package='spectral_meterusage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10meterValue.proto\x12\x13spectral_meterusage\"\x18\n\x04\x44\x61te\x12\x10\n\x08\x64\x61te_str\x18\x01 \x01(\t\"\x1b\n\tdateValue\x12\x0e\n\x06values\x18\x01 \x01(\t2_\n\x10meterUsageValues\x12K\n\x0cgetMeterData\x12\x19.spectral_meterusage.Date\x1a\x1e.spectral_meterusage.dateValue\"\x00\x62\x06proto3')
)




_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='spectral_meterusage.Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date_str', full_name='spectral_meterusage.Date.date_str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=65,
)


_DATEVALUE = _descriptor.Descriptor(
  name='dateValue',
  full_name='spectral_meterusage.dateValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='spectral_meterusage.dateValue.values', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['dateValue'] = _DATEVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'meterValue_pb2'
  # @@protoc_insertion_point(class_scope:spectral_meterusage.Date)
  })
_sym_db.RegisterMessage(Date)

dateValue = _reflection.GeneratedProtocolMessageType('dateValue', (_message.Message,), {
  'DESCRIPTOR' : _DATEVALUE,
  '__module__' : 'meterValue_pb2'
  # @@protoc_insertion_point(class_scope:spectral_meterusage.dateValue)
  })
_sym_db.RegisterMessage(dateValue)



_METERUSAGEVALUES = _descriptor.ServiceDescriptor(
  name='meterUsageValues',
  full_name='spectral_meterusage.meterUsageValues',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=96,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='getMeterData',
    full_name='spectral_meterusage.meterUsageValues.getMeterData',
    index=0,
    containing_service=None,
    input_type=_DATE,
    output_type=_DATEVALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METERUSAGEVALUES)

DESCRIPTOR.services_by_name['meterUsageValues'] = _METERUSAGEVALUES

# @@protoc_insertion_point(module_scope)
