# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meterValue.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='meterValue.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10meterValue.proto\"\x18\n\x04\x44\x61te\x12\x10\n\x08\x64\x61te_str\x18\x01 \x01(\t\"b\n\tdateValue\x12&\n\x06values\x18\x01 \x03(\x0b\x32\x16.dateValue.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32\x33\n\x10meterUsageValues\x12\x1f\n\x08get_data\x12\x05.Date\x1a\n.dateValue\"\x00\x62\x06proto3')
)




_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date_str', full_name='Date.date_str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=44,
)


_DATEVALUE_VALUESENTRY = _descriptor.Descriptor(
  name='ValuesEntry',
  full_name='dateValue.ValuesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dateValue.ValuesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='dateValue.ValuesEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=144,
)

_DATEVALUE = _descriptor.Descriptor(
  name='dateValue',
  full_name='dateValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='dateValue.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATEVALUE_VALUESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=144,
)

_DATEVALUE_VALUESENTRY.containing_type = _DATEVALUE
_DATEVALUE.fields_by_name['values'].message_type = _DATEVALUE_VALUESENTRY
DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['dateValue'] = _DATEVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'meterValue_pb2'
  # @@protoc_insertion_point(class_scope:Date)
  })
_sym_db.RegisterMessage(Date)

dateValue = _reflection.GeneratedProtocolMessageType('dateValue', (_message.Message,), {

  'ValuesEntry' : _reflection.GeneratedProtocolMessageType('ValuesEntry', (_message.Message,), {
    'DESCRIPTOR' : _DATEVALUE_VALUESENTRY,
    '__module__' : 'meterValue_pb2'
    # @@protoc_insertion_point(class_scope:dateValue.ValuesEntry)
    })
  ,
  'DESCRIPTOR' : _DATEVALUE,
  '__module__' : 'meterValue_pb2'
  # @@protoc_insertion_point(class_scope:dateValue)
  })
_sym_db.RegisterMessage(dateValue)
_sym_db.RegisterMessage(dateValue.ValuesEntry)


_DATEVALUE_VALUESENTRY._options = None

_METERUSAGEVALUES = _descriptor.ServiceDescriptor(
  name='meterUsageValues',
  full_name='meterUsageValues',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=146,
  serialized_end=197,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_data',
    full_name='meterUsageValues.get_data',
    index=0,
    containing_service=None,
    input_type=_DATE,
    output_type=_DATEVALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METERUSAGEVALUES)

DESCRIPTOR.services_by_name['meterUsageValues'] = _METERUSAGEVALUES

# @@protoc_insertion_point(module_scope)
