# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import meterValue_pb2 as meterValue__pb2


class meterUsageValuesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get_data = channel.unary_unary(
        '/meterUsageValues/get_data',
        request_serializer=meterValue__pb2.Date.SerializeToString,
        response_deserializer=meterValue__pb2.dateValue.FromString,
        )


class meterUsageValuesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get_data(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_meterUsageValuesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get_data': grpc.unary_unary_rpc_method_handler(
          servicer.get_data,
          request_deserializer=meterValue__pb2.Date.FromString,
          response_serializer=meterValue__pb2.dateValue.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'meterUsageValues', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
