# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import meterValue_pb2 as meterValue__pb2


class meterUsageValuesStub(object):
  """Service Definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getMeterData = channel.unary_unary(
        '/spectral_meterusage.meterUsageValues/getMeterData',
        request_serializer=meterValue__pb2.Dates.SerializeToString,
        response_deserializer=meterValue__pb2.dateValues.FromString,
        )


class meterUsageValuesServicer(object):
  """Service Definition
  """

  def getMeterData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_meterUsageValuesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getMeterData': grpc.unary_unary_rpc_method_handler(
          servicer.getMeterData,
          request_deserializer=meterValue__pb2.Dates.FromString,
          response_serializer=meterValue__pb2.dateValues.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'spectral_meterusage.meterUsageValues', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
